# Header
menu:
  主页: /
  所有文章: /archives
  编程与算法: /categories/编程与算法
  日常维护: /categories/日常维护
  点点滴滴: /categories/点点滴滴
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: https://github.com/InnerAc
#  weibo: "#"
#  rss: "#"
#  zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

#rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
#avatar: https://avatars1.githubusercontent.com/u/8242597?v=3&s=460
avatar: /ava.png
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: true
duoshuo: innerac
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  JetMuffin的博客: http://www.jetmuffin.com
  Sloriac的博客: http://sunzequn.com/
  祁林的博客: http://www.qilinlirui.com/
  马鹏举的博客: http://mapengju.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 本人男，目前学生党。常年ACM打铁铸铜，正在成长中。
